import type { Strategy } from '@/types'

// =============================================
// 手立てマスターデータ（全8カテゴリ）
// =============================================

// ---------------------------------------------
// ✏️ 国語・漢字 (kanji)
// ---------------------------------------------

const KANJI_STRATEGIES: Strategy[] = [
  {
    id: 'kanji_4step',
    category: 'kanji',
    label: '4ステップ法',
    description: '「見る→なぞる→隠して書く→確認」を1文字3分ペースで行う',
    target_domains: ['kanji_literacy', 'working_memory'],
    learning_style: ['visual', 'kinesthetic'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'kanji_flash',
    measurable_by: ['Q2', 'Q8'],
  },
  {
    id: 'kanji_color_bushu',
    category: 'kanji',
    label: '部首カラー分解',
    description: '偏と旁を色分けして「パーツの組み合わせ」として視覚化する',
    target_domains: ['kanji_literacy', 'sensory'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'kanji_group',
    measurable_by: ['Q2', 'Q8'],
  },
  {
    id: 'kanji_story',
    category: 'kanji',
    label: '成り立ちストーリー',
    description: '象形文字の元の形を教えて「山は山の形からできたんだよ」とストーリーで記憶',
    target_domains: ['kanji_literacy', 'motivation_emotion'],
    learning_style: ['auditory'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'kanji_sentence',
    measurable_by: ['Q2'],
  },
  {
    id: 'kanji_big_write',
    category: 'kanji',
    label: '大きく書く練習',
    description: 'B4ホワイトボードや大きなマス目ノートでまず大きく書き、体の動きで覚える',
    target_domains: ['kanji_literacy', 'sensory'],
    learning_style: ['kinesthetic'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'kanji_4step',
    measurable_by: ['Q8'],
  },
  {
    id: 'kanji_rhythm',
    category: 'kanji',
    label: '音読しながら書く',
    description: '書き順を「いち、に、はらい」とリズムで声に出しながら書く',
    target_domains: ['kanji_literacy', 'working_memory'],
    learning_style: ['auditory', 'kinesthetic'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'kanji_4step',
    measurable_by: ['Q2', 'Q8'],
  },
  {
    id: 'kanji_3times',
    category: 'kanji',
    label: '3回だけ書くルール',
    description: '10回書くのは苦痛。3回書いて覚えられたらOKにする',
    target_domains: ['kanji_literacy', 'study_habits'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: 'kanji_4step',
    measurable_by: ['Q2', 'Q7'],
  },
  {
    id: 'kanji_wall',
    category: 'kanji',
    label: '壁貼り漢字',
    description: '今週の漢字をトイレや冷蔵庫に貼って日常的に目に入れる',
    target_domains: ['kanji_literacy'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'kanji_morning_test',
    measurable_by: ['Q2'],
  },
  {
    id: 'kanji_stamp',
    category: 'kanji',
    label: 'スタンプカード',
    description: '10文字覚えたらシール1枚、5枚でごほうび',
    target_domains: ['kanji_literacy', 'motivation_emotion'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'kanji_teacher',
    category: 'kanji',
    label: '先生ごっこ',
    description: '覚えた漢字を親やきょうだいに教える役にする',
    target_domains: ['kanji_literacy', 'motivation_emotion'],
    learning_style: ['auditory'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'kanji_sentence',
    category: 'kanji',
    label: '短文作り',
    description: '新しい漢字を使って1文作る（意味と結びつけて定着させる）',
    target_domains: ['kanji_literacy', 'motivation_emotion'],
    learning_style: [],
    difficulty: 2,
    prerequisite: 'kanji_4step',
    next_step: 'kanji_quiz',
    measurable_by: ['Q2'],
  },
  {
    id: 'kanji_group',
    category: 'kanji',
    label: '仲間分け（部首別）',
    description: '同じ部首の漢字をグループにして「木の仲間：林、森、村、松」とまとめる',
    target_domains: ['kanji_literacy', 'attention'],
    learning_style: ['visual'],
    difficulty: 2,
    prerequisite: 'kanji_color_bushu',
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'kanji_flash',
    category: 'kanji',
    label: 'フラッシュカード',
    description: '表に漢字・裏に読みと例文のカードを作り、隙間時間に確認',
    target_domains: ['kanji_literacy', 'processing_speed'],
    learning_style: ['visual'],
    difficulty: 2,
    prerequisite: 'kanji_4step',
    next_step: 'kanji_kentei',
    measurable_by: ['Q2'],
  },
  {
    id: 'kanji_morning_test',
    category: 'kanji',
    label: '翌朝1分テスト',
    description: '前日に覚えた漢字を朝食前に1分だけテスト（寝た後の記憶確認）',
    target_domains: ['kanji_literacy', 'study_habits'],
    learning_style: [],
    difficulty: 2,
    prerequisite: 'kanji_wall',
    next_step: 'kanji_weekly_test',
    measurable_by: ['Q2'],
  },
  {
    id: 'kanji_weekly_test',
    category: 'kanji',
    label: '週末ミニテスト',
    description: '金曜に今週の漢字10問テストし、正解率を記録して成長を見せる',
    target_domains: ['kanji_literacy'],
    learning_style: [],
    difficulty: 2,
    prerequisite: 'kanji_morning_test',
    next_step: 'kanji_kentei',
    measurable_by: ['Q2'],
  },
  {
    id: 'kanji_quiz',
    category: 'kanji',
    label: '親子クイズ対決',
    description: '覚えた漢字を親子で出し合いっこ（出題側になると定着する）',
    target_domains: ['kanji_literacy', 'motivation_emotion'],
    learning_style: [],
    difficulty: 2,
    prerequisite: 'kanji_sentence',
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'kanji_kentei',
    category: 'kanji',
    label: '漢検チャレンジ',
    description: '目標を持たせて「漢検◯級を目指そう」と長期ゴールを設定',
    target_domains: ['kanji_literacy', 'motivation_emotion'],
    learning_style: [],
    difficulty: 3,
    prerequisite: 'kanji_weekly_test',
    next_step: null,
    measurable_by: ['Q7'],
  },
]

// ---------------------------------------------
// 🔢 算数・計算 (math)
// ---------------------------------------------

const MATH_STRATEGIES: Strategy[] = [
  {
    id: 'math_5clear',
    category: 'math',
    label: '5問ずつクリア方式',
    description: 'ドリル1ページを折って見える量を減らし「まず5問」に集中',
    target_domains: ['math_calculation', 'attention'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: 'math_time_attack',
    measurable_by: ['Q2', 'Q7'],
  },
  {
    id: 'math_3rest',
    category: 'math',
    label: '3問→1分休憩ルール',
    description: '長時間やらず区切りを入れる。3問解いたら1分ストレッチ',
    target_domains: ['math_calculation', 'study_habits'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: 'math_5clear',
    measurable_by: ['Q9', 'Q7'],
  },
  {
    id: 'math_easy_first',
    category: 'math',
    label: '簡単→難しいの順',
    description: '最初に得意な計算で成功体験を積んでから苦手に取り組む',
    target_domains: ['math_calculation', 'motivation_emotion'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'math_grid_note',
    category: 'math',
    label: '方眼ノート筆算',
    description: '筆算の桁をきれいに揃えて書くことでズレによるミスを防ぐ',
    target_domains: ['math_calculation'],
    learning_style: ['kinesthetic'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'math_check_back',
    measurable_by: ['Q8'],
  },
  {
    id: 'math_read_aloud',
    category: 'math',
    label: '声に出して読む',
    description: '問題文を音読してから解く（目だけで読むと読み飛ばす）',
    target_domains: ['math_calculation', 'attention'],
    learning_style: ['auditory'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'math_show_steps',
    category: 'math',
    label: '途中式を必ず書く',
    description: '暗算で飛ばさず、途中のステップを全部書く習慣をつける',
    target_domains: ['math_calculation', 'working_memory'],
    learning_style: ['kinesthetic'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'math_check_back',
    measurable_by: ['Q8'],
  },
  {
    id: 'math_kuku_song',
    category: 'math',
    label: '九九ソング',
    description: '九九を歌やリズムに乗せて暗記（体が覚えるまで）',
    target_domains: ['math_calculation', 'working_memory'],
    learning_style: ['auditory'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'math_flash_card',
    measurable_by: ['Q2'],
  },
  {
    id: 'math_mark_numbers',
    category: 'math',
    label: '数字に○・聞かれていることに下線',
    description: '色ペンで問題文にマークしてから考える（文章題対策）',
    target_domains: ['math_calculation', 'attention'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'math_draw_picture',
    measurable_by: ['Q2'],
  },
  {
    id: 'math_keyword',
    category: 'math',
    label: 'キーワード表',
    description: '「あわせて→+」「ちがいは→-」「分ける→÷」の対応表を手元に置く',
    target_domains: ['math_calculation'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'math_what_asked',
    measurable_by: ['Q2'],
  },
  {
    id: 'math_sakuranbo',
    category: 'math',
    label: 'さくらんぼ計算やり直し',
    description: '繰り上がり・繰り下がりを図で丁寧にやり直す（急がない）',
    target_domains: ['math_calculation'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'math_grid_note',
    measurable_by: ['Q2', 'Q8'],
  },
  {
    id: 'math_real_divide',
    category: 'math',
    label: 'おはじきで分ける体験',
    description: 'おはじき・ブロック・定規など手で触れる教材を使う',
    target_domains: ['math_calculation', 'sensory'],
    learning_style: ['kinesthetic'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'math_point_sheet',
    category: 'math',
    label: 'ポイント記録シート',
    description: '正解数を折れ線グラフにして「右肩上がり」を見せる',
    target_domains: ['math_calculation', 'motivation_emotion'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'math_time_attack',
    measurable_by: ['Q7'],
  },
  {
    id: 'math_bath_quiz',
    category: 'math',
    label: 'お風呂で暗算タイム',
    description: '湯船につかりながら「7×8は?」と口頭クイズ',
    target_domains: ['math_calculation'],
    learning_style: ['auditory'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'math_time_attack',
    category: 'math',
    label: 'タイムアタック（自己ベスト型）',
    description: '他人と比べず「昨日の自分より速く」を目標にする',
    target_domains: ['math_calculation', 'motivation_emotion'],
    learning_style: [],
    difficulty: 2,
    prerequisite: 'math_5clear',
    next_step: 'math_100grid',
    measurable_by: ['Q2', 'Q7'],
  },
  {
    id: 'math_flash_card',
    category: 'math',
    label: '計算カードめくり',
    description: 'たし算・ひき算カードを瞬時に答える練習（フラッシュカード方式）',
    target_domains: ['math_calculation', 'processing_speed'],
    learning_style: ['visual'],
    difficulty: 2,
    prerequisite: 'math_kuku_song',
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'math_check_back',
    category: 'math',
    label: '見直しの型（逆算確認）',
    description: '「答えを式に戻して確認」（15-7=8 → 8+7=15✓）',
    target_domains: ['math_calculation'],
    learning_style: [],
    difficulty: 2,
    prerequisite: 'math_show_steps',
    next_step: 'math_no_miss',
    measurable_by: ['Q8'],
  },
  {
    id: 'math_miss_log',
    category: 'math',
    label: 'ミスパターン記録',
    description: '繰り下がり忘れ、桁ズレなど「いつも同じところ」を見える化',
    target_domains: ['math_calculation', 'attention'],
    learning_style: ['visual'],
    difficulty: 2,
    prerequisite: 'math_check_back',
    next_step: null,
    measurable_by: ['Q8'],
  },
  {
    id: 'math_draw_picture',
    category: 'math',
    label: '絵・図を描く',
    description: '文章題で「みかんが5個あって3個食べたら」を絵に描いてイメージ化',
    target_domains: ['math_calculation', 'sensory'],
    learning_style: ['visual', 'kinesthetic'],
    difficulty: 2,
    prerequisite: 'math_mark_numbers',
    next_step: 'math_make_problem',
    measurable_by: ['Q2'],
  },
  {
    id: 'math_what_asked',
    category: 'math',
    label: '「何を聞かれている?」を先に言う',
    description: '式を立てる前に「何を求めるの?」を言語化する',
    target_domains: ['math_calculation', 'working_memory'],
    learning_style: ['auditory'],
    difficulty: 2,
    prerequisite: 'math_keyword',
    next_step: 'math_estimate',
    measurable_by: ['Q2'],
  },
  {
    id: 'math_estimate',
    category: 'math',
    label: '見積もり→計算→確認',
    description: '「だいたい答えはどのくらい?」を先に予想してから解く',
    target_domains: ['math_calculation'],
    learning_style: [],
    difficulty: 2,
    prerequisite: 'math_what_asked',
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'math_redo_miss',
    category: 'math',
    label: '間違いだけ翌日リトライ',
    description: '全部やり直すのでなく、間違いだけの「お直しタイム」',
    target_domains: ['math_calculation', 'study_habits'],
    learning_style: [],
    difficulty: 2,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'math_parent_battle',
    category: 'math',
    label: '親子計算バトル',
    description: '同じ問題を親も解いて勝負（楽しみながら計算力UP）',
    target_domains: ['math_calculation', 'motivation_emotion'],
    learning_style: [],
    difficulty: 2,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'math_shopping',
    category: 'math',
    label: '買い物おつり計算',
    description: 'スーパーで「500円出したらおつりいくら?」と実生活に結びつける',
    target_domains: ['math_calculation'],
    learning_style: [],
    difficulty: 2,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'math_100grid',
    category: 'math',
    label: '100マス計算',
    description: 'たし算→ひき算→かけ算の順で毎日1枚（2〜3分で終わる量）',
    target_domains: ['math_calculation', 'processing_speed'],
    learning_style: [],
    difficulty: 2,
    prerequisite: 'math_time_attack',
    next_step: null,
    measurable_by: ['Q2', 'Q9'],
  },
  {
    id: 'math_make_problem',
    category: 'math',
    label: '問題を自分で作る',
    description: '「たし算の文章題を1問作ってみて」→ 構造を理解する',
    target_domains: ['math_calculation', 'motivation_emotion'],
    learning_style: [],
    difficulty: 3,
    prerequisite: 'math_draw_picture',
    next_step: null,
    measurable_by: ['Q2', 'Q7'],
  },
  {
    id: 'math_no_miss',
    category: 'math',
    label: 'ノーミスチャレンジ',
    description: '5問連続正解で小さなごほうび（ゲーム感覚に）',
    target_domains: ['math_calculation', 'attention'],
    learning_style: [],
    difficulty: 3,
    prerequisite: 'math_check_back',
    next_step: null,
    measurable_by: ['Q7', 'Q8'],
  },
]

// ---------------------------------------------
// 🎯 集中のしやすさ (attention)
// ---------------------------------------------

const ATTENTION_STRATEGIES: Strategy[] = [
  {
    id: 'attn_clean_desk',
    category: 'attention',
    label: '机スッキリルール',
    description: '勉強前に「今やること」以外を全部引き出しにしまう',
    target_domains: ['attention'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'attn_one_sheet',
    measurable_by: ['Q2'],
  },
  {
    id: 'attn_partition',
    category: 'attention',
    label: '段ボール衝立',
    description: '机の左右に簡易パーテーションを立てて視界の刺激を遮断',
    target_domains: ['attention', 'sensory'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q2', 'Q9'],
  },
  {
    id: 'attn_one_sheet',
    category: 'attention',
    label: '1枚だけ出すルール',
    description: 'プリントや教科書を1つだけ出し、終わったら次を出す',
    target_domains: ['attention', 'working_memory'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'attn_5min_pomo',
    category: 'attention',
    label: '5分ポモドーロ',
    description: '5分集中→1分休憩→5分集中のショートサイクルから始める',
    target_domains: ['attention', 'study_habits'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: 'attn_focus_record',
    measurable_by: ['Q9'],
  },
  {
    id: 'attn_visual_timer',
    category: 'attention',
    label: '見えるタイマー',
    description: '残り時間が視覚的に減っていくタイマー（Time Timerなど）を使う',
    target_domains: ['attention'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'attn_focus_record',
    measurable_by: ['Q9'],
  },
  {
    id: 'attn_move_first',
    category: 'attention',
    label: '体を動かしてからスタート',
    description: '宿題前に30秒ジャンプや廊下ダッシュで脳を起こす',
    target_domains: ['attention', 'motivation_emotion'],
    learning_style: ['kinesthetic'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'attn_bgm_control',
    category: 'attention',
    label: 'BGMコントロール',
    description: 'テレビを消す、または自然音・ホワイトノイズで聴覚刺激を安定化',
    target_domains: ['attention', 'sensory'],
    learning_style: ['auditory'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'attn_focus_record',
    category: 'attention',
    label: '集中時間の記録',
    description: '「今日は何分できた」を記録して右肩上がりを見せる',
    target_domains: ['attention', 'motivation_emotion'],
    learning_style: ['visual'],
    difficulty: 2,
    prerequisite: 'attn_5min_pomo',
    next_step: null,
    measurable_by: ['Q9'],
  },
]

// ---------------------------------------------
// 🧩 手順の記憶 (working_memory)
// ---------------------------------------------

const WM_STRATEGIES: Strategy[] = [
  {
    id: 'wm_sticky_list',
    category: 'working_memory',
    label: '付箋やることリスト',
    description: '宿題を付箋3枚に書き、終わったら1枚ずつ剥がす',
    target_domains: ['working_memory', 'study_habits'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'wm_self_checklist',
    measurable_by: ['Q7'],
  },
  {
    id: 'wm_3step',
    category: 'working_memory',
    label: '3ステップ分解',
    description: '複雑な宿題を「まず→次に→最後に」の3つ以内に分解する',
    target_domains: ['working_memory'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: 'wm_self_checklist',
    measurable_by: ['Q2'],
  },
  {
    id: 'wm_say_aloud',
    category: 'working_memory',
    label: '声に出してから始める',
    description: '「まず漢字ドリル、次に計算」と口に出す→忘れにくい',
    target_domains: ['working_memory'],
    learning_style: ['auditory'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'wm_point_check',
    category: 'working_memory',
    label: '指差し確認',
    description: '1つ終わったら「できた!」とリストを指差して次へ進む',
    target_domains: ['working_memory'],
    learning_style: ['kinesthetic'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'wm_report_done',
    category: 'working_memory',
    label: '1つ終わったら報告',
    description: '「計算終わった!」と報告に来るルールで区切りを作る',
    target_domains: ['working_memory', 'study_habits'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'wm_color_priority',
    category: 'working_memory',
    label: '色分け優先順位',
    description: '赤付箋＝すぐやる、黄付箋＝あとでOK、と視覚で整理',
    target_domains: ['working_memory', 'attention'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'wm_night_prep',
    category: 'working_memory',
    label: '前日夜の準備セット',
    description: '夜に明日の持ち物と宿題を一緒にチェック→朝の混乱を防ぐ',
    target_domains: ['working_memory', 'study_habits'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'wm_self_checklist',
    category: 'working_memory',
    label: 'チェックリスト自作',
    description: '自分で「やることリスト」を書く練習をして自走力を育てる',
    target_domains: ['working_memory', 'study_habits'],
    learning_style: [],
    difficulty: 2,
    prerequisite: 'wm_sticky_list',
    next_step: null,
    measurable_by: ['Q7'],
  },
]

// ---------------------------------------------
// ⚡ 作業スピード (processing_speed)
// ---------------------------------------------

const SPEED_STRATEGIES: Strategy[] = [
  {
    id: 'speed_slow_ok',
    category: 'processing_speed',
    label: '「ゆっくりでOK」宣言',
    description: '焦りはミスの元。まず「丁寧にやろう」と安心させる',
    target_domains: ['processing_speed', 'motivation_emotion'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: 'speed_praise_stable',
    measurable_by: ['Q7'],
  },
  {
    id: 'speed_praise_stable',
    category: 'processing_speed',
    label: '安定さを褒める',
    description: '速さでなく「ミスなく3問できたね」と正確性を評価する',
    target_domains: ['processing_speed', 'motivation_emotion'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q8'],
  },
  {
    id: 'speed_reduce_writing',
    category: 'processing_speed',
    label: '書く量の調整',
    description: 'ノートの行数を減らす、答えだけ書くなど書く負担を軽減',
    target_domains: ['processing_speed'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q2', 'Q9'],
  },
  {
    id: 'speed_routine',
    category: 'processing_speed',
    label: 'ルーティン化',
    description: '毎日同じ順序でやることで「何をするか考える時間」を省略',
    target_domains: ['processing_speed', 'study_habits'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: 'speed_pattern_drill',
    measurable_by: ['Q7'],
  },
  {
    id: 'speed_fixed_place',
    category: 'processing_speed',
    label: '定位置ルール',
    description: '鉛筆・消しゴム・教科書の置き場所を決めて探す時間をゼロにする',
    target_domains: ['processing_speed'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'speed_time_alloc',
    category: 'processing_speed',
    label: '時間配分の練習',
    description: 'テスト前に「まず全部見て、できそうなのから」の習慣づけ',
    target_domains: ['processing_speed', 'attention'],
    learning_style: [],
    difficulty: 2,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q9'],
  },
  {
    id: 'speed_pattern_drill',
    category: 'processing_speed',
    label: '定型パターン反復',
    description: '繰り上がりなど頻出パターンを体が覚えるまで繰り返す',
    target_domains: ['processing_speed', 'math_calculation'],
    learning_style: [],
    difficulty: 2,
    prerequisite: 'speed_routine',
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'speed_time_sense',
    category: 'processing_speed',
    label: '区切り時間の目安',
    description: '「この5問は5分くらい」と大まかな時間感覚を持たせる',
    target_domains: ['processing_speed'],
    learning_style: [],
    difficulty: 2,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q9'],
  },
]

// ---------------------------------------------
// 💪 やる気・気持ち (motivation_emotion)
// ---------------------------------------------

const MOTIVATION_STRATEGIES: Strategy[] = [
  {
    id: 'moti_start_praise',
    category: 'motivation_emotion',
    label: '「始めただけでOK」',
    description: '取りかかったこと自体を褒める（結果より行動を評価）',
    target_domains: ['motivation_emotion', 'study_habits'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'moti_success_note',
    category: 'motivation_emotion',
    label: '成功ノート',
    description: '寝る前に「今日できたこと」を1つ書く→自己肯定感の蓄積',
    target_domains: ['motivation_emotion'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'moti_reward_point',
    category: 'motivation_emotion',
    label: 'ごほうびポイント',
    description: '宿題完了→1ポイント、10ポイントで好きなおやつなど',
    target_domains: ['motivation_emotion', 'study_habits'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'moti_choice',
    category: 'motivation_emotion',
    label: '選択権を与える',
    description: '「算数と国語どっちからやる?」→自分で決めた感覚が大事',
    target_domains: ['motivation_emotion'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'moti_growth_praise',
    category: 'motivation_emotion',
    label: '「100点じゃなくていい」',
    description: '前回より1問多く解けたら花丸→成長を評価する',
    target_domains: ['motivation_emotion'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'moti_watch_over',
    category: 'motivation_emotion',
    label: '親の「見てるよ」',
    description: '隣で見守る（口は出さない）→安心して取り組める',
    target_domains: ['motivation_emotion'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'moti_one_question',
    category: 'motivation_emotion',
    label: '1問チャレンジ',
    description: 'やる気が出ない日は「まず1問だけ」→始めると続くことが多い',
    target_domains: ['motivation_emotion', 'study_habits'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'moti_fav_first',
    category: 'motivation_emotion',
    label: '得意科目スタート',
    description: '好きな教科から始めて勢いをつけてから苦手科目へ',
    target_domains: ['motivation_emotion'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'moti_tired_choice',
    category: 'motivation_emotion',
    label: '疲れた時の選択肢',
    description: '「5分休んで続けるか、明日の朝やるか選んでいいよ」',
    target_domains: ['motivation_emotion'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q3'],
  },
  {
    id: 'moti_fail_ok',
    category: 'motivation_emotion',
    label: '失敗OK宣言',
    description: '間違えても消さずに赤で直す→「間違いは成長の証」と伝える',
    target_domains: ['motivation_emotion'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
]

// ---------------------------------------------
// 📚 学習習慣 (study_habits)
// ---------------------------------------------

const HABIT_STRATEGIES: Strategy[] = [
  {
    id: 'habit_time_fix',
    category: 'study_habits',
    label: '時間固定ルーティン',
    description: '毎日同じ時間に始める（16:00→おやつ→16:15→宿題）',
    target_domains: ['study_habits'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: 'habit_weekly_review',
    measurable_by: ['Q7'],
  },
  {
    id: 'habit_routine_poster',
    category: 'study_habits',
    label: 'ルーティン表を壁に',
    description: '「帰宅→手洗い→おやつ→宿題→自由時間」を見える化',
    target_domains: ['study_habits'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'habit_fixed_place',
    category: 'study_habits',
    label: '場所を固定',
    description: 'リビングのこの席、と学習場所を決めて「スイッチ」を作る',
    target_domains: ['study_habits'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'habit_trigger',
    category: 'study_habits',
    label: '開始トリガー',
    description: '「机に座ったらまず鉛筆を持つ」→体の動きで脳にスタート合図',
    target_domains: ['study_habits', 'motivation_emotion'],
    learning_style: ['kinesthetic'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'habit_15min_timer',
    category: 'study_habits',
    label: '15分タイマー法',
    description: '「とりあえず15分だけ」で心理的ハードルを下げる',
    target_domains: ['study_habits', 'motivation_emotion'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7', 'Q9'],
  },
  {
    id: 'habit_show_total',
    category: 'study_habits',
    label: '量の事前把握',
    description: '「今日は計算10問と漢字5文字だけ」と全体量を見せてから開始',
    target_domains: ['study_habits', 'working_memory'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'habit_done_check',
    category: 'study_habits',
    label: '終了チェックリスト',
    description: '終わった項目に○をつける→達成感の可視化',
    target_domains: ['study_habits'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'habit_night_bag',
    category: 'study_habits',
    label: '寝る前ランドセル確認',
    description: '翌日の準備を寝る前に済ませる→朝バタバタしない',
    target_domains: ['study_habits', 'working_memory'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'habit_reward_clear',
    category: 'study_habits',
    label: 'メリハリ宣言',
    description: '「宿題が終わったらゲーム30分OK」と報酬を明確に',
    target_domains: ['study_habits', 'motivation_emotion'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q7'],
  },
  {
    id: 'habit_weekly_review',
    category: 'study_habits',
    label: '週末ミニ振り返り',
    description: '「今週がんばれたこと・来週の目標」を親子で話す',
    target_domains: ['study_habits', 'motivation_emotion'],
    learning_style: [],
    difficulty: 2,
    prerequisite: 'habit_time_fix',
    next_step: null,
    measurable_by: ['Q7'],
  },
]

// ---------------------------------------------
// 👁️ 感覚の特徴 (sensory)
// ---------------------------------------------

const SENSORY_STRATEGIES: Strategy[] = [
  {
    id: 'sense_color_marker',
    category: 'sensory',
    label: '色ペン・マーカー活用',
    description: '重要箇所に色をつけて視覚的に整理する（視覚優位向け）',
    target_domains: ['sensory'],
    learning_style: ['visual'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'sense_flowchart',
    measurable_by: ['Q2'],
  },
  {
    id: 'sense_flowchart',
    category: 'sensory',
    label: '図解・フローチャート',
    description: '手順を矢印でつないだ図にして理解を助ける（視覚優位向け）',
    target_domains: ['sensory', 'working_memory'],
    learning_style: ['visual'],
    difficulty: 2,
    prerequisite: 'sense_color_marker',
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'sense_read_aloud',
    category: 'sensory',
    label: '音読学習',
    description: '教科書を声に出して読む→耳から入ると覚えやすい子に（聴覚優位向け）',
    target_domains: ['sensory'],
    learning_style: ['auditory'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'sense_explain',
    measurable_by: ['Q2'],
  },
  {
    id: 'sense_explain',
    category: 'sensory',
    label: '説明ごっこ',
    description: '覚えたことを親に口頭で説明する→話すことで定着（聴覚優位向け）',
    target_domains: ['sensory', 'motivation_emotion'],
    learning_style: ['auditory'],
    difficulty: 2,
    prerequisite: 'sense_read_aloud',
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'sense_touch_material',
    category: 'sensory',
    label: '実物を使う',
    description: 'おはじき・ブロック・定規など手で触れる教材を使う（体感覚優位向け）',
    target_domains: ['sensory', 'math_calculation'],
    learning_style: ['kinesthetic'],
    difficulty: 1,
    prerequisite: null,
    next_step: 'sense_body_learn',
    measurable_by: ['Q2'],
  },
  {
    id: 'sense_body_learn',
    category: 'sensory',
    label: '体を使って覚える',
    description: '大きく体を動かして文字を書く、歩きながら九九を唱える（体感覚優位向け）',
    target_domains: ['sensory'],
    learning_style: ['kinesthetic'],
    difficulty: 2,
    prerequisite: 'sense_touch_material',
    next_step: null,
    measurable_by: ['Q2'],
  },
  {
    id: 'sense_lighting',
    category: 'sensory',
    label: '照明の調整',
    description: '暗すぎず明るすぎない照明で目の疲れを防ぐ',
    target_domains: ['sensory', 'attention'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q9'],
  },
  {
    id: 'sense_desk_fit',
    category: 'sensory',
    label: '椅子・机の高さ合わせ',
    description: '足が床につく高さに調整→姿勢安定で集中持続',
    target_domains: ['sensory', 'attention'],
    learning_style: [],
    difficulty: 1,
    prerequisite: null,
    next_step: null,
    measurable_by: ['Q9'],
  },
]

// =============================================
// 全手立てをまとめたマスターデータ
// =============================================

export const ALL_STRATEGIES: Strategy[] = [
  ...KANJI_STRATEGIES,
  ...MATH_STRATEGIES,
  ...ATTENTION_STRATEGIES,
  ...WM_STRATEGIES,
  ...SPEED_STRATEGIES,
  ...MOTIVATION_STRATEGIES,
  ...HABIT_STRATEGIES,
  ...SENSORY_STRATEGIES,
]

// =============================================
// ヘルパー関数
// =============================================

/** IDで手立てを検索 */
export function getStrategyById(id: string): Strategy | undefined {
  return ALL_STRATEGIES.find(s => s.id === id)
}

/** カテゴリで絞り込み */
export function getStrategiesByCategory(category: Strategy['category']): Strategy[] {
  return ALL_STRATEGIES.filter(s => s.category === category)
}

/** 対象ドメインで絞り込み */
export function getStrategiesByDomain(domain: string): Strategy[] {
  return ALL_STRATEGIES.filter(s => s.target_domains.includes(domain as Strategy['target_domains'][number]))
}

/** 難易度で絞り込み */
export function getStrategiesByDifficulty(maxDifficulty: 1 | 2 | 3): Strategy[] {
  return ALL_STRATEGIES.filter(s => s.difficulty <= maxDifficulty)
}

/** 学習スタイルで絞り込み（指定スタイルに合う or スタイル指定なし） */
export function getStrategiesByStyle(style: Strategy['learning_style'][number]): Strategy[] {
  return ALL_STRATEGIES.filter(s => s.learning_style.length === 0 || s.learning_style.includes(style))
}

/** 前提を満たしている手立てのみ取得 */
export function getAvailableStrategies(completedIds: string[]): Strategy[] {
  return ALL_STRATEGIES.filter(s =>
    s.prerequisite === null || completedIds.includes(s.prerequisite)
  )
}

/** 次のステップの手立てを取得 */
export function getNextSteps(currentId: string): Strategy[] {
  const current = getStrategyById(currentId)
  if (!current?.next_step) return []
  const next = getStrategyById(current.next_step)
  return next ? [next] : []
}
